# Generated by Django 2.0.5 on 2018-05-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grower_Number', models.CharField(max_length=8, unique=True)),
                ('Grower_Name', models.CharField(max_length=200)),
                ('National_ID', models.CharField(max_length=15, unique=True)),
                ('Mobile_Number', models.CharField(max_length=20)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='growers.District')),
            ],
            options={
                'ordering': ['Grower_Name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='growers.Province'),
        ),
    ]
