# Generated by Django 2.0.5 on 2018-05-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growers', '0004_auto_20180506_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsqueue',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
