# Generated by Django 2.0.5 on 2018-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growers', '0002_auto_20180506_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.CharField(max_length=15, unique=True)),
                ('message', models.CharField(max_length=15, unique=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
