# Generated by Django 2.0.5 on 2018-05-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growers', '0005_auto_20180506_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grower',
            name='Grower_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
